/**
 * Componente para registro de usuarios por parte del administrador
 * Incluye integración con wallets de Metamask y certificados .pem
 */

import React, { useState, useRef } from 'react';
import { useAuth } from '../hooks/useAuth';
import { walletService } from '../services/walletService';
import { toast } from 'react-hot-toast';
import { 
    UserPlusIcon, 
    DocumentCheckIcon, 
    ShieldCheckIcon, 
    ClipboardDocumentCheckIcon,
    XMarkIcon,
    CheckCircleIcon,
    ExclamationTriangleIcon
} from '@heroicons/react/24/outline';

interface UserRegistrationData {
    walletAddress: string;
    role: 'producer' | 'factory' | 'retailer' | 'consumer';
    adminSignature: string;
    certificatePem?: string;
    certificateFile?: File;
    useAutoGeneratedCertificate: boolean;
}

interface AdminUserRegistrationProps {
    onClose: () => void;
    onUserCreated: (user: any) => void;
}

const AdminUserRegistration: React.FC<AdminUserRegistrationProps> = ({ 
    onClose, 
    onUserCreated 
}) => {
    const { user } = useAuth();
    const fileInputRef = useRef<HTMLInputElement>(null);
    
    const [formData, setFormData] = useState<UserRegistrationData>({
        walletAddress: '',
        role: 'producer',
        adminSignature: '',
        certificatePem: '',
        certificateFile: undefined,
        useAutoGeneratedCertificate: true
    });
    
    const [isLoading, setIsLoading] = useState(false);
    const [currentStep, setCurrentStep] = useState<'address' | 'role' | 'certificate' | 'confirm'>('address');
    const [certificateValidation, setCertificateValidation] = useState<{
        isValid: boolean;
        message: string;
    } | null>(null);

    const roles = [
        { value: 'producer', label: 'Productor', description: 'Crea y gestiona productos agrícolas' },
        { value: 'factory', label: 'Fábrica', description: 'Procesa y transforma productos' },
        { value: 'retailer', label: 'Minorista', description: 'Vende productos al consumidor final' },
        { value: 'consumer', label: 'Consumidor', description: 'Usuario final del producto' }
    ];

    /**
     * Valida una dirección de wallet
     */
    const validateWalletAddress = (address: string): boolean => {
        if (!address) return false;
        // Validación básica de formato Ethereum
        return /^0x[a-fA-F0-9]{40}$/.test(address);
    };

    /**
     * Conecta con MetaMask para obtener la dirección
     */
    const connectWallet = async (): Promise<void> => {
        try {
            setIsLoading(true);
            
            const account = await walletService.connectWallet();
            
            if (account) {
                setFormData(prev => ({
                    ...prev,
                    walletAddress: account.address
                }));
                toast.success('Wallet conectada exitosamente');
            }
        } catch (error: any) {
            console.error('Error conectando wallet:', error);
            toast.error('Error conectando con MetaMask');
        } finally {
            setIsLoading(false);
        }
    };

    /**
     * Maneja la carga de archivo de certificado
     */
    const handleCertificateFile = async (event: React.ChangeEvent<HTMLInputElement>): Promise<void> => {
        const file = event.target.files?.[0];
        
        if (!file) return;

        // Validar tipo de archivo
        if (!file.name.endsWith('.pem')) {
            toast.error('Por favor seleccione un archivo .pem válido');
            return;
        }

        try {
            const fileContent = await file.text();
            
            // Validar formato básico del certificado
            if (!fileContent.includes('-----BEGIN CERTIFICATE-----') || 
                !fileContent.includes('-----END CERTIFICATE-----')) {
                setCertificateValidation({
                    isValid: false,
                    message: 'Formato de certificado .pem inválido'
                });
                return;
            }

            setFormData(prev => ({
                ...prev,
                certificatePem: fileContent,
                certificateFile: file
            }));

            setCertificateValidation({
                isValid: true,
                message: 'Certificado cargado correctamente'
            });

            toast.success('Certificado cargado exitosamente');
        } catch (error) {
            console.error('Error leyendo archivo:', error);
            toast.error('Error leyendo el archivo de certificado');
        }
    };

    /**
     * Genera firma del administrador
     */
    const generateAdminSignature = async (): Promise<void> => {
        try {
            if (!formData.walletAddress || !formData.role) {
                toast.error('Complete la dirección y rol antes de firmar');
                return;
            }

            setIsLoading(true);

            // Mensaje a firmar
            const message = `registerUser:${formData.walletAddress}:${formData.role}`;
            
            // Firmar con la wallet del admin
            const signature = await walletService.signMessage(message);
            
            setFormData(prev => ({
                ...prev,
                adminSignature: signature
            }));

            toast.success('Firma generada exitosamente');
        } catch (error: any) {
            console.error('Error generando firma:', error);
            toast.error('Error generando la firma de administrador');
        } finally {
            setIsLoading(false);
        }
    };

    /**
     * Envía el formulario de registro
     */
    const handleSubmit = async (): Promise<void> => {
        try {
            setIsLoading(true);

            // Validaciones finales
            if (!validateWalletAddress(formData.walletAddress)) {
                toast.error('Dirección de wallet inválida');
                return;
            }

            if (!formData.adminSignature) {
                toast.error('Firma de administrador requerida');
                return;
            }

            // Preparar datos para envío
            const submitData = {
                walletAddress: formData.walletAddress,
                role: formData.role,
                adminSignature: formData.adminSignature,
                ...(formData.certificatePem && !formData.useAutoGeneratedCertificate && {
                    certificatePem: formData.certificatePem
                })
            };

            // Enviar petición al backend
            const response = await fetch('/api/admin/users', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${localStorage.getItem('token')}`
                },
                body: JSON.stringify(submitData)
            });

            const result = await response.json();

            if (result.success) {
                toast.success('Usuario registrado exitosamente');
                onUserCreated(result.user);
                onClose();
            } else {
                toast.error(result.message || 'Error registrando usuario');
            }

        } catch (error: any) {
            console.error('Error enviando formulario:', error);
            toast.error('Error registrando usuario');
        } finally {
            setIsLoading(false);
        }
    };

    /**
     * Navega al siguiente paso
     */
    const nextStep = (): void => {
        const steps = ['address', 'role', 'certificate', 'confirm'];
        const currentIndex = steps.indexOf(currentStep);
        if (currentIndex < steps.length - 1) {
            setCurrentStep(steps[currentIndex + 1] as any);
        }
    };

    /**
     * Navega al paso anterior
     */
    const prevStep = (): void => {
        const steps = ['address', 'role', 'certificate', 'confirm'];
        const currentIndex = steps.indexOf(currentStep);
        if (currentIndex > 0) {
            setCurrentStep(steps[currentIndex - 1] as any);
        }
    };

    return (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
            <div className="relative top-20 mx-auto p-5 border w-11/12 max-w-2xl shadow-lg rounded-md bg-white">
                {/* Header */}
                <div className="flex justify-between items-center mb-6">
                    <h3 className="text-lg font-semibold text-gray-900 flex items-center">
                        <UserPlusIcon className="h-6 w-6 mr-2 text-blue-600" />
                        Registrar Nuevo Usuario
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600"
                    >
                        <XMarkIcon className="h-6 w-6" />
                    </button>
                </div>

                {/* Progress Bar */}
                <div className="mb-6">
                    <div className="flex justify-between mb-2">
                        <span className="text-sm text-gray-500">Paso {
                            currentStep === 'address' ? 1 : 
                            currentStep === 'role' ? 2 : 
                            currentStep === 'certificate' ? 3 : 4
                        } de 4</span>
                        <span className="text-sm text-gray-500">
                            {currentStep === 'address' ? 'Dirección de Wallet' : 
                             currentStep === 'role' ? 'Rol del Usuario' : 
                             currentStep === 'certificate' ? 'Certificado' : 'Confirmación'}
                        </span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                        <div 
                            className="bg-blue-600 h-2 rounded-full transition-all duration-300"
                            style={{ 
                                width: `${
                                    currentStep === 'address' ? 25 : 
                                    currentStep === 'role' ? 50 : 
                                    currentStep === 'certificate' ? 75 : 100
                                }%` 
                            }}
                        />
                    </div>
                </div>

                {/* Step 1: Wallet Address */}
                {currentStep === 'address' && (
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Dirección de Wallet del Usuario
                            </label>
                            <div className="flex space-x-2">
                                <input
                                    type="text"
                                    value={formData.walletAddress}
                                    onChange={(e) => setFormData(prev => ({ ...prev, walletAddress: e.target.value }))}
                                    placeholder="0x..."
                                    className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                />
                                <button
                                    onClick={connectWallet}
                                    disabled={isLoading}
                                    className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                                >
                                    {isLoading ? 'Conectando...' : 'MetaMask'}
                                </button>
                            </div>
                            {formData.walletAddress && !validateWalletAddress(formData.walletAddress) && (
                                <p className="mt-1 text-sm text-red-600">
                                    Dirección de wallet inválida
                                </p>
                            )}
                        </div>
                        
                        <div className="flex justify-end">
                            <button
                                onClick={nextStep}
                                disabled={!validateWalletAddress(formData.walletAddress)}
                                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                            >
                                Siguiente
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 2: Role Selection */}
                {currentStep === 'role' && (
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Rol del Usuario
                            </label>
                            <div className="grid grid-cols-2 gap-3">
                                {roles.map((role) => (
                                    <div
                                        key={role.value}
                                        className={`p-3 border rounded-md cursor-pointer transition-all ${
                                            formData.role === role.value
                                                ? 'border-blue-500 bg-blue-50'
                                                : 'border-gray-300 hover:border-gray-400'
                                        }`}
                                        onClick={() => setFormData(prev => ({ ...prev, role: role.value as any }))}
                                    >
                                        <div className="font-medium">{role.label}</div>
                                        <div className="text-sm text-gray-500">{role.description}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                        
                        <div className="flex justify-between">
                            <button
                                onClick={prevStep}
                                className="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400"
                            >
                                Anterior
                            </button>
                            <button
                                onClick={nextStep}
                                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
                            >
                                Siguiente
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 3: Certificate Configuration */}
                {currentStep === 'certificate' && (
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Configuración de Certificado
                            </label>
                            
                            {/* Certificate Method Selection */}
                            <div className="space-y-3">
                                <label className="flex items-center">
                                    <input
                                        type="radio"
                                        name="certificateMethod"
                                        checked={formData.useAutoGeneratedCertificate}
                                        onChange={() => setFormData(prev => ({ ...prev, useAutoGeneratedCertificate: true }))}
                                        className="mr-2"
                                    />
                                    <ShieldCheckIcon className="h-5 w-5 mr-2 text-green-600" />
                                    <span>Generar certificado automáticamente</span>
                                </label>
                                
                                <label className="flex items-center">
                                    <input
                                        type="radio"
                                        name="certificateMethod"
                                        checked={!formData.useAutoGeneratedCertificate}
                                        onChange={() => setFormData(prev => ({ ...prev, useAutoGeneratedCertificate: false }))}
                                        className="mr-2"
                                    />
                                    <DocumentCheckIcon className="h-5 w-5 mr-2 text-blue-600" />
                                    <span>Subir certificado personalizado (.pem)</span>
                                </label>
                            </div>

                            {/* Certificate Upload */}
                            {!formData.useAutoGeneratedCertificate && (
                                <div className="mt-4 p-4 border-2 border-dashed border-gray-300 rounded-md">
                                    <div className="text-center">
                                        <ClipboardDocumentCheckIcon className="mx-auto h-12 w-12 text-gray-400" />
                                        <div className="mt-2">
                                            <button
                                                onClick={() => fileInputRef.current?.click()}
                                                className="text-blue-600 hover:text-blue-700"
                                            >
                                                Seleccionar archivo .pem
                                            </button>
                                            <p className="text-sm text-gray-500 mt-1">
                                                O arrastre y suelte aquí
                                            </p>
                                        </div>
                                    </div>
                                    
                                    <input
                                        ref={fileInputRef}
                                        type="file"
                                        accept=".pem"
                                        onChange={handleCertificateFile}
                                        className="hidden"
                                    />
                                    
                                    {certificateValidation && (
                                        <div className={`mt-2 p-2 rounded-md ${
                                            certificateValidation.isValid ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                                        }`}>
                                            <div className="flex items-center">
                                                {certificateValidation.isValid ? (
                                                    <CheckCircleIcon className="h-4 w-4 mr-1" />
                                                ) : (
                                                    <ExclamationTriangleIcon className="h-4 w-4 mr-1" />
                                                )}
                                                <span className="text-sm">{certificateValidation.message}</span>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                        
                        <div className="flex justify-between">
                            <button
                                onClick={prevStep}
                                className="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400"
                            >
                                Anterior
                            </button>
                            <button
                                onClick={nextStep}
                                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
                            >
                                Siguiente
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 4: Confirmation */}
                {currentStep === 'confirm' && (
                    <div className="space-y-4">
                        <div>
                            <h4 className="text-lg font-medium text-gray-900 mb-4">
                                Confirmar Registro
                            </h4>
                            
                            <div className="bg-gray-50 p-4 rounded-md space-y-2">
                                <div><strong>Dirección:</strong> {formData.walletAddress}</div>
                                <div><strong>Rol:</strong> {roles.find(r => r.value === formData.role)?.label}</div>
                                <div><strong>Certificado:</strong> {
                                    formData.useAutoGeneratedCertificate ? 'Generado automáticamente' : 
                                    formData.certificateFile ? `Archivo: ${formData.certificateFile.name}` : 'Ninguno'
                                }</div>
                            </div>
                        </div>
                        
                        {/* Admin Signature */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Firma de Administrador
                            </label>
                            <div className="flex space-x-2">
                                <input
                                    type="text"
                                    value={formData.adminSignature}
                                    readOnly
                                    placeholder="Genere la firma haciendo clic en el botón"
                                    className="flex-1 px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                                />
                                <button
                                    onClick={generateAdminSignature}
                                    disabled={isLoading}
                                    className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
                                >
                                    {isLoading ? 'Firmando...' : 'Firmar'}
                                </button>
                            </div>
                        </div>
                        
                        <div className="flex justify-between">
                            <button
                                onClick={prevStep}
                                className="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400"
                            >
                                Anterior
                            </button>
                            <button
                                onClick={handleSubmit}
                                disabled={isLoading || !formData.adminSignature}
                                className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
                            >
                                {isLoading ? 'Registrando...' : 'Registrar Usuario'}
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AdminUserRegistration;